
name: Build

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@34cfbaee7f672c76950673338facd8a73f637506

    - name: build and test
      run: ./build-and-test.cmd
      
  auto-merge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: auto-merge
        if: |
          github.actor == 'dependabot[bot]' &&
          github.event_name == 'pull_request'
        run: |
          ./merge_dependabot.sh
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          # this secret needs to be in the settings.secrets.dependabot
          GITHUB_TOKEN: ${{secrets.GH_ACTION_TOKEN}}

